apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: ai-devops

bases:
  - ../../base

resources:
  - ingress.yaml
  - hpa.yaml

patchesStrategicMerge:
  - backend-deployment-patch.yaml
  - frontend-deployment-patch.yaml

configMapGenerator:
  - name: ai-devops-config
    behavior: merge
    literals:
      - aws_region=us-east-1
      - bedrock_model_id=anthropic.claude-3-sonnet-20240229-v1:0
      - vector_db_type=opensearch
      - log_level=INFO
